openapi: 3.0.0
info:
  title: API LOJA VIRTUAL
  version: 0.1
tags:
  - clientes
paths:
  /clientes:
    post:
      tags:
        - clientes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        422:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'