openapi: 3.0.0
info:
  title: API Fornecedores
  version: 0.0.1
tags:
  - name: fornecedores
    description: Operações relacionadas aos fornecedores
paths:
  /fornecedor:
    post:
      tags:
        - fornecedores
      summary: Adiciona um novo fornecedor
      requestBody:
        description: Dados do fornecedor a ser adicionado
        required: true
        content:
            schema:
              $ref: '#/components/schemas/Fornecedor'
      responses:
        201:
          description: Fornecedor criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
        422:
          description: Dados inválidos fornecidos para o fornecedor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    get:
      tags:
        - fornecedores
      summary: Lista todos os fornecedores
      responses:
        200:
          description: Lista de fornecedores
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfFornecedores'
  /fornecedor/{id}:
    get:
      tags:
        - fornecedores
      summary: Obtém os detalhes de um fornecedor específico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID do fornecedor
      responses:
        200:
          description: Detalhes do fornecedor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
        400:
          description: ID do fornecedor inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          description: Fornecedor não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    put:
      tags:
        - fornecedores
      summary: Atualiza as informações de um fornecedor específico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID do fornecedor
      requestBody:
        description: Dados atualizados do fornecedor
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fornecedor'
      responses:
        200:
          description: Fornecedor atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
        400:
          description: ID do fornecedor inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          description: Fornecedor não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        422:
          description: Dados inválidos fornecidos para atualização
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
    delete:
      tags:
        - fornecedores
      summary: Exclui um fornecedor específico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID do fornecedor
      responses:
        204:
          description: Fornecedor excluído com sucesso
        400:
          description: ID do fornecedor inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        404:
          description: Fornecedor não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
components:
  schemas:
    ArrayOfFornecedores:
      type: array
      items:
        $ref: '#/components/schemas/Fornecedor'
    Fornecedor:
      type: object
      properties:
        id:
          type: string
          description: ID do fornecedor
        nome:
          type: string
          description: Nome do fornecedor
        cnpj:
          type: string
          description: CNPJ do fornecedor
      required:
        - nome
        - cnpj
    Mensagem:
      type: object
      properties:
        msg:
          type: string
          description: Mensagem de erro ou status